### ISSUE TITLE
Supported platform

### ISSUE THREAD

**Issue by unixfreaxjp** [ghostbar/radare2.deb#1]
In my country there are embed basis architecture (arm/mips/ppc) devel people are using Debian basis, please consider to write the supported architecture in the .md in your git? thank you.

**Comment by ghostbar** [comment]
I'll write it in the description; because of how .debs are built and I want this to be used ultimately on the original distros I'm not changing the source except for `debian/patches` using quilt.

I'll try to setup my builder on armv7 so I can provide those besides just x86_64.
